[pytest]
DJANGO_SETTINGS_MODULE = docmagic_core.settings
python_files = tests/*.py
python_functions = test_*
python_paths = /app
addopts = --cov=docs --cov-report=html:/NET/djangocore/coverage --cov-report=term --cov-fail-under=75
