[pytest]
DJANGO_SETTINGS_MODULE = proxy.settings
python_files = tests/*.py
python_functions = test_*
python_paths = /app
addopts = --cov=logger --cov-report=html:/NET/djangorest/coverage --cov-report=term --cov-fail-under=75
